### ISSUE TITLE
Instrucciones 0x2e y 0x2f  (LDC). No Implementada en el modulo JT900h

### ISSUE THREAD

**Issue by florgana** [jotego/jt900h#4]
Los codigos 0x2e y 0x2f  correspondientes a la instrucción LDC, no esta  definida en el modulo JT900h

Codigo cpp
`case 0x2e:`
    `  data = fetch();`
    `  idle(1);`
    `  return instructionLoad(toControlRegister<T>(data), register);`
  `case 0x2f:`
    `   data = fetch();`
    `   idle(1);`
`   return instructionLoad(register, toControlRegister<T>(data));`

**Comment by jotego** [comment]
Añadidas.
