### ISSUE TITLE
Revisar la instruction Mirror (ALU_MIRR)

### ISSUE THREAD

**Issue by florgana** [jotego/jt900h#6]
La instruccion funciona para 8bits?
`ALU_MIRR: begin`
`            rslt[15:0] = {`
`                op0[0], op0[1], op0[2], op0[3], op0[4], op0[5], op0[6], op0[7],`
`                op0[8], op0[9], op0[10], op0[11], op0[12], op0[13], op0[14], op0[15]`
`            };`
`        end`

`auto TLCS900H::instructionMirror(Register<uint16> register) -> void {`
`  idle(1);`
`  auto data = load(register);`
`  data = data << 1 & 0xaaaa | data >> 1 & 0x5555;`
`  data = data << 2 & 0xcccc | data >> 2 & 0x3333;`
`  data = data << 4 & 0xf0f0 | data >> 4 & 0x0f0f;`
`  store(register, data << 8 | data >> 8);`
`}`

**Comment by jotego** [comment]
No, es sólo para 16 bits
